<?php

namespace MessengerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{
    public function findByParticipants($participant)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
            ->from('MessengerBundle:Conversation', 'conversation')
            ->join('conversation.users', 'users')
            ->select([
                'conversation',
                'users',
            ])
            ->where('users.id = :id')
            ->setParameter('id', $participant)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findWithMessages($conversationId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb
            ->from('MessengerBundle:Conversation', 'conversation')
            ->join('conversation.messages', 'messages')
            ->select([
                'conversation',
                'messages',
            ])
            ->where('conversation.id = :id')
            ->setParameter('id', $conversationId)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
