<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function searchFriend($username)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();

        $query->select('u')
              ->from('UserBundle:User', 'u')
              ->where($query->expr()->like('u.username', ':username'))
              ->setParameter('username', '%'.$username.'%');

        $results = $query->getQuery();
        $username = $results->getResult();

        return $username;

    }
}
